name: omnicell
channel_priority: strict
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
dependencies:
  - python=3.9
  - jupyterlab
  - pytorch
  - scanpy
  - matplotlib
  - yaml
  - tqdm
  - numpy
  - pot
  - lightning
  - pip
  - pip:
    - torchcfm
    - torchdyn
