HVG: False
cell_embeddings: []
cell_key: celltype
control: non-targeting
count_normalized: false
description: Downloaded from scPerturb website
folder_path: /orcd/data/omarabu/001/Omnicell_datasets/Adamson2016/GSM2406681_10X010/
gene_embeddings: []
log1p_transformed: false
path: /orcd/data/omarabu/001/Omnicell_datasets/Adamson2016/GSM2406681_10X010/AdamsonWeissman2016_GSM2406681_10X010.h5ad
pert_embeddings: []
pert_key: perturbation
precomputed_DEGs: false
var_names_key: gene_symbol
