HVG: false
cell_embeddings: []
cell_key: celltype
control: control
count_normalized: false
description: Downloaded from scPerturb website
folder_path: /orcd/data/omarabu/001/Omnicell_datasets/DatlingerBock2017
gene_embeddings: []
log1p_transformed: false
path: /orcd/data/omarabu/001/Omnicell_datasets/DatlingerBock2017/DatlingerBock2017.h5ad
pert_embeddings: []
pert_key: perturbation
precomputed_DEGs: false
var_names_key: null
