HVG: false
cell_embeddings: []
cell_key: celltype
control: non-targeting
count_normalized: false
description: Downloaded from scPerturb website
folder_path: /orcd/data/omarabu/001/Omnicell_datasets/FrangiehIzar2021/RNA
gene_embeddings: []
log1p_transformed: false
path: /orcd/data/omarabu/001/Omnicell_datasets/FrangiehIzar2021/RNA/FrangiehIzar2021_RNA.h5ad
pert_embeddings: []
pert_key: perturbation
precomputed_DEGs: false
var_names_key: gene_symbol
