HVG: false
cell_embeddings: []
cell_key: celltype
control: non-targeting
count_normalized: false
description: Downloaded from scPerturb website
folder_path: /orcd/data/omarabu/001/Omnicell_datasets/TianKampmann2019/day7neuron
gene_embeddings: []
log1p_transformed: false
path: /orcd/data/omarabu/001/Omnicell_datasets/TianKampmann2019/day7neuron/TianKampmann2019_day7neuron.h5ad
pert_embeddings: []
pert_key: perturbation
precomputed_DEGs: false
var_names_key: null
