HVG: false
cell_embeddings: ['clone_matrix']
cell_key: celltype
control: non-targeting
count_normalized: false
description: Downloaded from scPerturb website
folder_path: /orcd/data/omarabu/001/neelroy/WeinrebKlein2020
gene_embeddings: []
log1p_transformed: false
path: /orcd/data/omarabu/001/neelroy/WeinrebKlein2020/WeinrebKlein2020.h5ad
pert_embeddings: []
pert_key: perturbation
precomputed_DEGs: false
var_names_key: gene_symbol
